### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by sparta34** [fireeye/DueDLLigence#1]
hi bro when i try to compile thid project using visual studio 2019 i get this error 

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0162	Unreachable code detected	DueDLLigence	C:\Users\defender\Desktop\DueDLLigence\DueDLLigence\DueDLLigence.cs	74	Active
Error		The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
System.ArgumentException: Requested value 'Version46' was not found.

Server stack trace: 
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.<>c__DisplayClass8.<GetGetToolPathInternal>b__7(Version version, String toolName) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 568
   at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.TryToGetToolDirForFxVersion(String toolFileName, Func`3 getToolPath, String& toolDirectory) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 725
   at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateToolPath(String toolFileName, String currentValue, Func`3 getToolPath, String& foundPath) in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 698
   at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateFrameworkPath() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 680
   at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.ValidateInputValues() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 396
   at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 264
   at RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask.Execute() in c:\Users\rober_000\Documents\Code\unmanaged-exports\RGiesecke.DllExport.MSBuild\DllExportAppDomainIsolatedTask.cs:line 241
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	DueDLLigence			
Warning	CS0162	Unreachable code detected	DueDLLigence	C:\Users\defender\Desktop\DueDLLigence\DueDLLigence\DueDLLigence.cs	77	Active

any tips thanks

**Comment by hawaii67** [comment]
I get exactly the same errors. Just DL'ed the project and tried to compile, no changes made. 
Please help. Thanks.

**Comment by mechs85** [comment]
I had the same issue and was Googling around like no tomorrow! Basically the CPU setting needs to be changed

From the toolbar, change Any CPU to x64 or x86 by selecting [new...]. I tried a few things and believe this got rid of that error.

But now I am getting a "Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe" error. It can be run from the VS command line, but for some reason it cannot run when I try and compile it

**Comment by hawaii67** [comment]
Thanks for your answer. Unfortunately changing the CPU settings doesn't change the error in any way.
I was playing with different versions of DLLExport but still no success.

**Comment by leaderzhang** [comment]
I have the same problem, but it hasn't been solved yet。:(

**Comment by chango77747** [comment]
All - we will be releasing a new version here in the near future that will address this issue. Bottom line, make sure that CPU is set to x86 or x64 specifically in the project settings. Also I suggest you have a target build of .Net 4.5

**Comment by chango77747** [comment]
We just released a new version today that should address these issues. Thank you for your comments.

**Comment by chango77747** [comment]
Released new version to address this issue

**Comment by chango77747** [comment]
Released new version to address this issueReleased new version to address this issue
